### ISSUE TITLE
Support specifying target_type

### ISSUE THREAD

**Issue by marcoreni** [devops-workflow/terraform-aws-lb#12]
https://github.com/WiserSolutions/terraform-aws-lb/blob/master/main.tf#L378 Should be decommented and it should be possible to declare the instance type.

Currently this module is not usable with Fargate because of this.

**Comment by snemetz** [comment]
I'm not currently doing anything with Fargate. Do you know if this is the only change needed to support Fargate? If so, easy to create a variable for it.

**Comment by marcoreni** [comment]
AFAICT this is the only required change. I'm trying to create a fargate-backed lb using a local copy of v3.3.0 of this module, will let you know ASAP.

**Comment by snemetz** [comment]
Should be able to add this today

**Comment by snemetz** [comment]
I created branch 'target-type' with the changes for this. But have not had time to do any testing

**Comment by snemetz** [comment]
Merged and released as v3.5.0
